/****** Exploratory Data Analysis  ******/

--New Column 'Revenue' added to the Order Details Table

  Alter table [E_commerce].[dbo].['Order Details$']
  add Revenue float

  Update [E_commerce].[dbo].['Order Details$']
  set Revenue = (Amount*Quantity)

  Select * from [E_commerce].[dbo].['Order Details$']

  --Total Revenue according to Category

  Select Category, SUM(Revenue) As Total_Revenue from [E_commerce].[dbo].['Order Details$']
  group by Category
  order by SUM(Revenue) desc;

  --Total Profit according to Category

  Select Category, SUM(Profit) As Total_Profit from [E_commerce].[dbo].['Order Details$']
  group by Category
  order by SUM(Profit) desc;

  --Revenue generated by each Sub-Category

  Select *, ROW_NUMBER() over(Partition by Category order by Revenue desc) as rw_num
  from [E_commerce].[dbo].['Order Details$']

  --Total Quantity ordered in each Category

  Select Category, SUM(Quantity) As Total_Quantity from [E_commerce].[dbo].['Order Details$']
  group by Category
  order by SUM(Quantity) desc;

  --Total Quantity ordered in each Sub-Category

  Select [Sub-Category],Category, SUM(Revenue) As Total_Revenue from [E_commerce].[dbo].['Order Details$']
  group by [Sub-Category],Category
  order by SUM(Revenue) desc;

  --Joined two tables Order Details and List of Orders

  Select O.[Order ID], O.Amount,O.Revenue,O.Profit,L.[Order Date],L.State,L.City,O.Category,O.[Sub-Category]
  from [E_commerce].[dbo].['Order Details$'] O inner join [E_commerce].[dbo].['List of Orders$'] L on O.[Order ID] = L.[Order ID]

  Select [Sub-Category] ,Round(AVG(Revenue),2) from [E_commerce].[dbo].['Order Details$']
  group by [Sub-Category] 
  Order by AVG(Revenue) desc

  --Average Revenue generated by each category

  Select Category ,Round(AVG(Revenue),2) as Avg_Revenue from [E_commerce].[dbo].['Order Details$']
  group by Category 
  Order by AVG(Revenue) desc;

  --Joined all three tables: Order Details, List of Orders and Sales Target

  Select O.[Order ID],O.Amount,O.Category,O.Profit,O.Revenue,O.[Sub-Category],L.City,L.State,L.[Order Date],L.CustomerName,S.[Month of Order Date],S.Target
  from [E_commerce].[dbo].['Order Details$'] O inner join [E_commerce].[dbo].['List of Orders$'] L on O.[Order ID] = L.[Order ID] inner join 
  [E_commerce].[dbo].['Sales target$'] S on S.[Month of Order Date]=L.[Order Date]

  --Profit generated in each month of 2018 & 2019

  Select L.[Order Date],Sum(O.Profit) from [E_commerce].[dbo].['Order Details$'] O inner join [E_commerce].[dbo].['List of Orders$'] L on O.[Order ID] = L.[Order ID] inner join 
  [E_commerce].[dbo].['Sales target$'] S on S.[Month of Order Date]=L.[Order Date]
  Group by L.[Order Date]
  Order by Sum(O.Profit)Desc;

  --Total Revenue generated by each City

  Select L.City, SUM(O.Revenue) As Total_Revenue from [E_commerce].[dbo].['Order Details$'] O inner join [E_commerce].[dbo].['List of Orders$'] L on O.[Order ID] = L.[Order ID] inner join 
  [E_commerce].[dbo].['Sales target$'] S on S.[Month of Order Date]=L.[Order Date]
  group by L.City
  order by SUM(O.Revenue) desc;